baseURL = "https://jibenliu.github.io"
title = "jibenliu blog"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
publishdir = "docs"
ignoreErrors = ["error-remote-getjson"]

# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "jibenliu"
description = "jibenliu's personal website"
keywords = "blog,developer,personal"
info = ["Full Stack DevOps", "Magician"]
avatarURL = "./images/avatar.jpg"
gravatar = "jibenliu@126.com"
dateFormat = "2006-01-02"
since = 2022
commit = "https://github.com/jibenliu"
rtl = false
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'", "https://www.gravatar.com","https://avatars.githubusercontent.com"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'", 
  "'unsafe-inline'", 
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/jibenliu/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 5
url = "https://medium.com/@jibenliu"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "关于"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "博客"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "项目"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "联系我"
weight = 5
url = "contact/"
